variables:
  IMAGE_NAME: collections-java-service
  SERVICE_NAME: abdocs
  SERVICE_PORT: 8081
  CONTAINER_PORT: 8080
  REPLICATE: 2
  SERVICE_NAME2: abdocs2
  DOCKER_NETWORK: nginx-net0

include:
  - project: 'abdocsgroup/boilerplates'
    ref: master
    file: 'microservices-springboot/.gitlab-ci.yml'

    
