variables:
  IMAGE_NAME: collections-java-service
  SERVICE_NAME: abdocs
  SERVICE_PORT: 8081
  CONTAINER_PORT: 8080


include:
  - project: 'abdocsgroup/boilerplates'
    ref: master
    file: 'microservices-springboot/.gitlab-ci.yml'

    
